# Generated by Django 4.1.7 on 2023-03-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('last_role', models.CharField(max_length=100)),
                ('preferred_role', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('joined_on', models.DateField(auto_now_add=True)),
                ('phone_number', models.DecimalField(decimal_places=2, max_digits=9)),
                ('specializations', models.CharField(max_length=250)),
                ('avatar', models.ImageField(upload_to='staffer_avatar')),
                ('city', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
