# Generated by Django 4.1.7 on 2023-04-01 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staffer_app', '0002_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffer',
            name='avatar',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
