# Generated by Django 4.1.7 on 2023-04-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer_app', '0004_alter_staffer_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='phone_number',
            field=models.DecimalField(decimal_places=0, max_digits=9),
        ),
    ]
