# Generated by Django 4.1.7 on 2023-04-02 12:42

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer_app', '0006_remove_staffer_last_role_staffer_salary_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffer',
            name='phone_number',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
