# Generated by Django 4.1.7 on 2023-04-04 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffer_app', '0007_alter_staffer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffer',
            name='last_role',
            field=models.CharField(default='', max_length=100),
        ),
    ]
